import type { Exercise } from './types';

export const EXERCISE_LIBRARY: Exercise[] = [
  // ============================================================
  // CHEST
  // ============================================================
  {
    id: 'ex-bench',
    name: 'Bench Press',
    primaryMuscle: 'chest',
    secondaryMuscle: 'triceps',
    secondaryMuscles: ['triceps', 'shoulders'],
    category: 'upper_push',
    exerciseType: 'compound',
  },
  {
    id: 'ex-incline-bench',
    name: 'Incline Dumbbell Press',
    primaryMuscle: 'chest',
    secondaryMuscle: 'shoulders',
    secondaryMuscles: ['shoulders', 'triceps'],
    category: 'upper_push',
    exerciseType: 'compound',
  },
  {
    id: 'ex-cable-fly',
    name: 'Cable Fly',
    primaryMuscle: 'chest',
    secondaryMuscles: ['shoulders'],
    category: 'upper_push',
    exerciseType: 'isolation',
  },
  {
    id: 'ex-dips',
    name: 'Dips',
    primaryMuscle: 'chest',
    secondaryMuscle: 'triceps',
    secondaryMuscles: ['triceps', 'shoulders'],
    category: 'upper_push',
    exerciseType: 'compound',
  },
  {
    id: 'ex-pec-deck',
    name: 'Pec Deck',
    primaryMuscle: 'chest',
    category: 'upper_push',
    exerciseType: 'isolation',
  },
  {
    id: 'ex-incline-barbell-press',
    name: 'Incline Barbell Press',
    primaryMuscle: 'chest',
    secondaryMuscle: 'shoulders',
    secondaryMuscles: ['shoulders', 'triceps'],
    category: 'upper_push',
    exerciseType: 'compound',
  },
  {
    id: 'ex-decline-bench',
    name: 'Decline Bench Press',
    primaryMuscle: 'chest',
    secondaryMuscle: 'triceps',
    secondaryMuscles: ['triceps', 'shoulders'],
    category: 'upper_push',
    exerciseType: 'compound',
  },
  {
    id: 'ex-dumbbell-bench',
    name: 'Dumbbell Bench Press',
    primaryMuscle: 'chest',
    secondaryMuscle: 'triceps',
    secondaryMuscles: ['triceps', 'shoulders'],
    category: 'upper_push',
    exerciseType: 'compound',
  },
  {
    id: 'ex-decline-dumbbell-press',
    name: 'Decline Dumbbell Press',
    primaryMuscle: 'chest',
    secondaryMuscle: 'triceps',
    secondaryMuscles: ['triceps', 'shoulders'],
    category: 'upper_push',
    exerciseType: 'compound',
  },
  {
    id: 'ex-dumbbell-fly',
    name: 'Dumbbell Fly',
    primaryMuscle: 'chest',
    secondaryMuscle: 'shoulders',
    secondaryMuscles: ['shoulders'],
    category: 'upper_push',
    exerciseType: 'isolation',
  },
  {
    id: 'ex-incline-dumbbell-fly',
    name: 'Incline Dumbbell Fly',
    primaryMuscle: 'chest',
    secondaryMuscle: 'shoulders',
    secondaryMuscles: ['shoulders'],
    category: 'upper_push',
    exerciseType: 'isolation',
  },
  {
    id: 'ex-cable-crossover',
    name: 'Cable Crossover',
    primaryMuscle: 'chest',
    secondaryMuscle: 'shoulders',
    secondaryMuscles: ['shoulders'],
    category: 'upper_push',
    exerciseType: 'isolation',
  },
  {
    id: 'ex-machine-chest-press',
    name: 'Machine Chest Press',
    primaryMuscle: 'chest',
    secondaryMuscle: 'triceps',
    secondaryMuscles: ['triceps', 'shoulders'],
    category: 'upper_push',
    exerciseType: 'compound',
  },
  {
    id: 'ex-push-up',
    name: 'Push-Up',
    primaryMuscle: 'chest',
    secondaryMuscle: 'triceps',
    secondaryMuscles: ['triceps', 'shoulders', 'abs'],
    category: 'upper_push',
    exerciseType: 'bodyweight',
  },
  {
    id: 'ex-landmine-press',
    name: 'Landmine Press',
    primaryMuscle: 'chest',
    secondaryMuscle: 'shoulders',
    secondaryMuscles: ['shoulders', 'triceps'],
    category: 'upper_push',
    exerciseType: 'compound',
  },
  {
    id: 'ex-smith-bench-press',
    name: 'Smith Machine Bench Press',
    primaryMuscle: 'chest',
    secondaryMuscles: ['triceps', 'shoulders'],
    category: 'upper_push',
    exerciseType: 'compound',
  },
  {
    id: 'ex-floor-press',
    name: 'Floor Press',
    primaryMuscle: 'chest',
    secondaryMuscles: ['triceps', 'shoulders'],
    category: 'upper_push',
    exerciseType: 'compound',
  },
  {
    id: 'ex-svend-press',
    name: 'Svend Press',
    primaryMuscle: 'chest',
    category: 'upper_push',
    exerciseType: 'isolation',
  },
  {
    id: 'ex-incline-cable-fly',
    name: 'Incline Cable Fly',
    primaryMuscle: 'chest',
    secondaryMuscles: ['shoulders'],
    category: 'upper_push',
    exerciseType: 'isolation',
  },
  {
    id: 'ex-wide-push-up',
    name: 'Wide Push-Up',
    primaryMuscle: 'chest',
    secondaryMuscles: ['triceps', 'shoulders'],
    category: 'upper_push',
    exerciseType: 'bodyweight',
  },

  // ============================================================
  // BACK
  // ============================================================
  {
    id: 'ex-pullup',
    name: 'Pull-Ups',
    primaryMuscle: 'back',
    secondaryMuscle: 'biceps',
    secondaryMuscles: ['biceps', 'forearms'],
    category: 'upper_pull',
    exerciseType: 'compound',
  },
  {
    id: 'ex-barbell-row',
    name: 'Barbell Row',
    primaryMuscle: 'back',
    secondaryMuscle: 'biceps',
    secondaryMuscles: ['biceps', 'forearms'],
    category: 'upper_pull',
    exerciseType: 'compound',
  },
  {
    id: 'ex-lat-pulldown',
    name: 'Lat Pulldown',
    primaryMuscle: 'back',
    secondaryMuscle: 'biceps',
    secondaryMuscles: ['biceps'],
    category: 'upper_pull',
    exerciseType: 'compound',
  },
  {
    id: 'ex-cable-row',
    name: 'Seated Cable Row',
    primaryMuscle: 'back',
    secondaryMuscles: ['biceps', 'shoulders'],
    category: 'upper_pull',
    exerciseType: 'compound',
  },
  {
    id: 'ex-face-pull',
    name: 'Face Pull',
    primaryMuscle: 'back',
    secondaryMuscle: 'shoulders',
    secondaryMuscles: ['shoulders'],
    category: 'upper_pull',
    exerciseType: 'isolation',
  },
  {
    id: 'ex-tbar-row',
    name: 'T-Bar Row',
    primaryMuscle: 'back',
    secondaryMuscle: 'biceps',
    secondaryMuscles: ['biceps', 'forearms'],
    category: 'upper_pull',
    exerciseType: 'compound',
  },
  {
    id: 'ex-chin-up',
    name: 'Chin-Ups',
    primaryMuscle: 'back',
    secondaryMuscle: 'biceps',
    secondaryMuscles: ['biceps', 'forearms'],
    category: 'upper_pull',
    exerciseType: 'compound',
  },
  {
    id: 'ex-pendlay-row',
    name: 'Pendlay Row',
    primaryMuscle: 'back',
    secondaryMuscle: 'biceps',
    secondaryMuscles: ['biceps', 'forearms'],
    category: 'upper_pull',
    exerciseType: 'compound',
  },
  {
    id: 'ex-dumbbell-row',
    name: 'Dumbbell Row',
    primaryMuscle: 'back',
    secondaryMuscle: 'biceps',
    secondaryMuscles: ['biceps', 'forearms'],
    category: 'upper_pull',
    exerciseType: 'compound',
  },
  {
    id: 'ex-straight-arm-pulldown',
    name: 'Straight-Arm Pulldown',
    primaryMuscle: 'back',
    secondaryMuscle: 'abs',
    secondaryMuscles: ['abs'],
    category: 'upper_pull',
    exerciseType: 'isolation',
  },
  {
    id: 'ex-deadlift',
    name: 'Deadlift',
    primaryMuscle: 'back',
    secondaryMuscle: 'hamstrings',
    secondaryMuscles: ['hamstrings', 'glutes', 'forearms'],
    category: 'upper_pull',
    exerciseType: 'compound',
  },
  {
    id: 'ex-rack-pull',
    name: 'Rack Pull',
    primaryMuscle: 'back',
    secondaryMuscle: 'hamstrings',
    secondaryMuscles: ['hamstrings', 'glutes', 'forearms'],
    category: 'upper_pull',
    exerciseType: 'compound',
  },
  {
    id: 'ex-machine-row',
    name: 'Machine Row',
    primaryMuscle: 'back',
    secondaryMuscle: 'biceps',
    secondaryMuscles: ['biceps'],
    category: 'upper_pull',
    exerciseType: 'compound',
  },
  {
    id: 'ex-chest-supported-row',
    name: 'Chest-Supported Row',
    primaryMuscle: 'back',
    secondaryMuscle: 'biceps',
    secondaryMuscles: ['biceps', 'shoulders'],
    category: 'upper_pull',
    exerciseType: 'compound',
  },
  {
    id: 'ex-barbell-shrug',
    name: 'Barbell Shrug',
    primaryMuscle: 'back',
    secondaryMuscle: 'shoulders',
    secondaryMuscles: ['shoulders', 'forearms'],
    category: 'upper_pull',
    exerciseType: 'isolation',
  },
  {
    id: 'ex-seal-row',
    name: 'Seal Row',
    primaryMuscle: 'back',
    secondaryMuscles: ['biceps', 'shoulders'],
    category: 'upper_pull',
    exerciseType: 'compound',
  },
  {
    id: 'ex-meadows-row',
    name: 'Meadows Row',
    primaryMuscle: 'back',
    secondaryMuscles: ['biceps', 'forearms'],
    category: 'upper_pull',
    exerciseType: 'compound',
  },
  {
    id: 'ex-inverted-row',
    name: 'Inverted Row',
    primaryMuscle: 'back',
    secondaryMuscles: ['biceps', 'abs'],
    category: 'upper_pull',
    exerciseType: 'bodyweight',
  },
  {
    id: 'ex-single-arm-lat-pulldown',
    name: 'Single-Arm Lat Pulldown',
    primaryMuscle: 'back',
    secondaryMuscles: ['biceps'],
    category: 'upper_pull',
    exerciseType: 'isolation',
  },
  {
    id: 'ex-kroc-row',
    name: 'Kroc Row',
    primaryMuscle: 'back',
    secondaryMuscles: ['biceps', 'forearms'],
    category: 'upper_pull',
    exerciseType: 'compound',
  },
  {
    id: 'ex-snatch-grip-deadlift',
    name: 'Snatch-Grip Deadlift',
    primaryMuscle: 'back',
    secondaryMuscles: ['hamstrings', 'glutes', 'forearms'],
    category: 'upper_pull',
    exerciseType: 'compound',
  },

  // ============================================================
  // SHOULDERS
  // ============================================================
  {
    id: 'ex-ohp',
    name: 'Overhead Press',
    primaryMuscle: 'shoulders',
    secondaryMuscle: 'triceps',
    secondaryMuscles: ['triceps', 'chest'],
    category: 'shoulders',
    exerciseType: 'compound',
  },
  {
    id: 'ex-lateral-raise',
    name: 'Lateral Raise',
    primaryMuscle: 'shoulders',
    category: 'shoulders',
    exerciseType: 'isolation',
  },
  {
    id: 'ex-rear-delt-fly',
    name: 'Rear Delt Fly',
    primaryMuscle: 'shoulders',
    secondaryMuscle: 'back',
    secondaryMuscles: ['back'],
    category: 'shoulders',
    exerciseType: 'isolation',
  },
  {
    id: 'ex-arnold-press',
    name: 'Arnold Press',
    primaryMuscle: 'shoulders',
    secondaryMuscle: 'triceps',
    secondaryMuscles: ['triceps', 'chest'],
    category: 'shoulders',
    exerciseType: 'compound',
  },
  {
    id: 'ex-dumbbell-shoulder-press',
    name: 'Dumbbell Shoulder Press',
    primaryMuscle: 'shoulders',
    secondaryMuscle: 'triceps',
    secondaryMuscles: ['triceps'],
    category: 'shoulders',
    exerciseType: 'compound',
  },
  {
    id: 'ex-push-press',
    name: 'Push Press',
    primaryMuscle: 'shoulders',
    secondaryMuscle: 'triceps',
    secondaryMuscles: ['triceps', 'quads'],
    category: 'shoulders',
    exerciseType: 'compound',
  },
  {
    id: 'ex-cable-lateral-raise',
    name: 'Cable Lateral Raise',
    primaryMuscle: 'shoulders',
    category: 'shoulders',
    exerciseType: 'isolation',
  },
  {
    id: 'ex-front-raise',
    name: 'Front Raise',
    primaryMuscle: 'shoulders',
    secondaryMuscle: 'chest',
    secondaryMuscles: ['chest'],
    category: 'shoulders',
    exerciseType: 'isolation',
  },
  {
    id: 'ex-reverse-pec-deck',
    name: 'Reverse Pec Deck',
    primaryMuscle: 'shoulders',
    secondaryMuscle: 'back',
    secondaryMuscles: ['back'],
    category: 'shoulders',
    exerciseType: 'isolation',
  },
  {
    id: 'ex-upright-row',
    name: 'Upright Row',
    primaryMuscle: 'shoulders',
    secondaryMuscle: 'biceps',
    secondaryMuscles: ['biceps', 'back'],
    category: 'shoulders',
    exerciseType: 'compound',
  },
  {
    id: 'ex-dumbbell-shrug',
    name: 'Dumbbell Shrug',
    primaryMuscle: 'shoulders',
    secondaryMuscle: 'back',
    secondaryMuscles: ['back', 'forearms'],
    category: 'shoulders',
    exerciseType: 'isolation',
  },
  {
    id: 'ex-machine-shoulder-press',
    name: 'Machine Shoulder Press',
    primaryMuscle: 'shoulders',
    secondaryMuscle: 'triceps',
    secondaryMuscles: ['triceps'],
    category: 'shoulders',
    exerciseType: 'compound',
  },
  {
    id: 'ex-machine-lateral-raise',
    name: 'Machine Lateral Raise',
    primaryMuscle: 'shoulders',
    category: 'shoulders',
    exerciseType: 'isolation',
  },
  {
    id: 'ex-lu-raise',
    name: 'Lu Raise',
    primaryMuscle: 'shoulders',
    secondaryMuscles: ['back'],
    category: 'shoulders',
    exerciseType: 'isolation',
  },
  {
    id: 'ex-behind-neck-press',
    name: 'Behind-the-Neck Press',
    primaryMuscle: 'shoulders',
    secondaryMuscles: ['triceps'],
    category: 'shoulders',
    exerciseType: 'compound',
  },
  {
    id: 'ex-y-raise',
    name: 'Y-Raise',
    primaryMuscle: 'shoulders',
    secondaryMuscles: ['back'],
    category: 'shoulders',
    exerciseType: 'isolation',
  },

  // ============================================================
  // BICEPS
  // ============================================================
  {
    id: 'ex-barbell-curl',
    name: 'Barbell Curl',
    primaryMuscle: 'biceps',
    secondaryMuscles: ['forearms'],
    category: 'upper_pull',
    exerciseType: 'isolation',
  },
  {
    id: 'ex-hammer-curl',
    name: 'Hammer Curl',
    primaryMuscle: 'biceps',
    secondaryMuscle: 'forearms',
    secondaryMuscles: ['forearms'],
    category: 'upper_pull',
    exerciseType: 'isolation',
  },
  {
    id: 'ex-ez-bar-curl',
    name: 'EZ-Bar Curl',
    primaryMuscle: 'biceps',
    secondaryMuscle: 'forearms',
    secondaryMuscles: ['forearms'],
    category: 'upper_pull',
    exerciseType: 'isolation',
  },
  {
    id: 'ex-dumbbell-curl',
    name: 'Dumbbell Curl',
    primaryMuscle: 'biceps',
    secondaryMuscle: 'forearms',
    secondaryMuscles: ['forearms'],
    category: 'upper_pull',
    exerciseType: 'isolation',
  },
  {
    id: 'ex-incline-dumbbell-curl',
    name: 'Incline Dumbbell Curl',
    primaryMuscle: 'biceps',
    secondaryMuscle: 'forearms',
    secondaryMuscles: ['forearms'],
    category: 'upper_pull',
    exerciseType: 'isolation',
  },
  {
    id: 'ex-preacher-curl',
    name: 'Preacher Curl',
    primaryMuscle: 'biceps',
    secondaryMuscle: 'forearms',
    secondaryMuscles: ['forearms'],
    category: 'upper_pull',
    exerciseType: 'isolation',
  },
  {
    id: 'ex-concentration-curl',
    name: 'Concentration Curl',
    primaryMuscle: 'biceps',
    category: 'upper_pull',
    exerciseType: 'isolation',
  },
  {
    id: 'ex-cable-curl',
    name: 'Cable Curl',
    primaryMuscle: 'biceps',
    secondaryMuscle: 'forearms',
    secondaryMuscles: ['forearms'],
    category: 'upper_pull',
    exerciseType: 'isolation',
  },
  {
    id: 'ex-spider-curl',
    name: 'Spider Curl',
    primaryMuscle: 'biceps',
    secondaryMuscles: ['forearms'],
    category: 'upper_pull',
    exerciseType: 'isolation',
  },
  {
    id: 'ex-zottman-curl',
    name: 'Zottman Curl',
    primaryMuscle: 'biceps',
    secondaryMuscles: ['forearms'],
    category: 'upper_pull',
    exerciseType: 'isolation',
  },
  {
    id: 'ex-drag-curl',
    name: 'Drag Curl',
    primaryMuscle: 'biceps',
    secondaryMuscles: ['forearms'],
    category: 'upper_pull',
    exerciseType: 'isolation',
  },
  {
    id: 'ex-bayesian-curl',
    name: 'Bayesian Cable Curl',
    primaryMuscle: 'biceps',
    secondaryMuscles: ['forearms'],
    category: 'upper_pull',
    exerciseType: 'isolation',
  },
  {
    id: 'ex-machine-curl',
    name: 'Machine Curl',
    primaryMuscle: 'biceps',
    category: 'upper_pull',
    exerciseType: 'isolation',
  },

  // ============================================================
  // TRICEPS
  // ============================================================
  {
    id: 'ex-tricep-pushdown',
    name: 'Tricep Pushdown',
    primaryMuscle: 'triceps',
    category: 'upper_push',
    exerciseType: 'isolation',
  },
  {
    id: 'ex-overhead-ext',
    name: 'Overhead Tricep Extension',
    primaryMuscle: 'triceps',
    category: 'upper_push',
    exerciseType: 'isolation',
  },
  {
    id: 'ex-rope-pushdown',
    name: 'Rope Pushdown',
    primaryMuscle: 'triceps',
    category: 'upper_push',
    exerciseType: 'isolation',
  },
  {
    id: 'ex-skull-crusher',
    name: 'Skull Crusher',
    primaryMuscle: 'triceps',
    secondaryMuscle: 'chest',
    secondaryMuscles: ['chest', 'shoulders'],
    category: 'upper_push',
    exerciseType: 'isolation',
  },
  {
    id: 'ex-close-grip-bench',
    name: 'Close-Grip Bench Press',
    primaryMuscle: 'triceps',
    secondaryMuscle: 'chest',
    secondaryMuscles: ['chest', 'shoulders'],
    category: 'upper_push',
    exerciseType: 'compound',
  },
  {
    id: 'ex-tricep-dips',
    name: 'Tricep Dips',
    primaryMuscle: 'triceps',
    secondaryMuscle: 'chest',
    secondaryMuscles: ['chest', 'shoulders'],
    category: 'upper_push',
    exerciseType: 'bodyweight',
  },
  {
    id: 'ex-diamond-push-up',
    name: 'Diamond Push-Up',
    primaryMuscle: 'triceps',
    secondaryMuscle: 'chest',
    secondaryMuscles: ['chest', 'shoulders'],
    category: 'upper_push',
    exerciseType: 'bodyweight',
  },
  {
    id: 'ex-cable-kickback',
    name: 'Cable Kickback',
    primaryMuscle: 'triceps',
    category: 'upper_push',
    exerciseType: 'isolation',
  },
  {
    id: 'ex-french-press',
    name: 'French Press',
    primaryMuscle: 'triceps',
    secondaryMuscles: ['shoulders'],
    category: 'upper_push',
    exerciseType: 'isolation',
  },
  {
    id: 'ex-bench-dips',
    name: 'Bench Dips',
    primaryMuscle: 'triceps',
    secondaryMuscles: ['chest', 'shoulders'],
    category: 'upper_push',
    exerciseType: 'bodyweight',
  },
  {
    id: 'ex-single-arm-pushdown',
    name: 'Single-Arm Pushdown',
    primaryMuscle: 'triceps',
    category: 'upper_push',
    exerciseType: 'isolation',
  },
  {
    id: 'ex-dip-machine',
    name: 'Dip Machine',
    primaryMuscle: 'triceps',
    secondaryMuscles: ['chest', 'shoulders'],
    category: 'upper_push',
    exerciseType: 'compound',
  },

  // ============================================================
  // FOREARMS
  // ============================================================
  {
    id: 'ex-wrist-curl',
    name: 'Wrist Curl',
    primaryMuscle: 'forearms',
    category: 'upper_pull',
    exerciseType: 'isolation',
  },
  {
    id: 'ex-reverse-wrist-curl',
    name: 'Reverse Wrist Curl',
    primaryMuscle: 'forearms',
    category: 'upper_pull',
    exerciseType: 'isolation',
  },
  {
    id: 'ex-farmers-walk',
    name: "Farmer's Walk",
    primaryMuscle: 'forearms',
    secondaryMuscle: 'back',
    secondaryMuscles: ['back', 'shoulders', 'abs'],
    category: 'full_body',
    exerciseType: 'compound',
  },
  {
    id: 'ex-dead-hang',
    name: 'Dead Hang',
    primaryMuscle: 'forearms',
    secondaryMuscle: 'back',
    secondaryMuscles: ['back', 'shoulders'],
    category: 'upper_pull',
    exerciseType: 'bodyweight',
  },
  {
    id: 'ex-reverse-curl',
    name: 'Reverse Curl',
    primaryMuscle: 'forearms',
    secondaryMuscles: ['biceps'],
    category: 'upper_pull',
    exerciseType: 'isolation',
  },
  {
    id: 'ex-plate-pinch',
    name: 'Plate Pinch Hold',
    primaryMuscle: 'forearms',
    category: 'upper_pull',
    exerciseType: 'isolation',
  },

  // ============================================================
  // QUADS
  // ============================================================
  {
    id: 'ex-squat',
    name: 'Barbell Squat',
    primaryMuscle: 'quads',
    secondaryMuscle: 'glutes',
    secondaryMuscles: ['glutes', 'hamstrings', 'abs'],
    category: 'legs',
    exerciseType: 'compound',
  },
  {
    id: 'ex-leg-press',
    name: 'Leg Press',
    primaryMuscle: 'quads',
    secondaryMuscle: 'glutes',
    secondaryMuscles: ['glutes', 'hamstrings'],
    category: 'legs',
    exerciseType: 'compound',
  },
  {
    id: 'ex-leg-ext',
    name: 'Leg Extension',
    primaryMuscle: 'quads',
    category: 'legs',
    exerciseType: 'isolation',
  },
  {
    id: 'ex-walking-lunge',
    name: 'Walking Lunge',
    primaryMuscle: 'quads',
    secondaryMuscle: 'glutes',
    secondaryMuscles: ['glutes', 'hamstrings'],
    category: 'legs',
    exerciseType: 'compound',
  },
  {
    id: 'ex-front-squat',
    name: 'Front Squat',
    primaryMuscle: 'quads',
    secondaryMuscle: 'glutes',
    secondaryMuscles: ['glutes', 'abs'],
    category: 'legs',
    exerciseType: 'compound',
  },
  {
    id: 'ex-goblet-squat',
    name: 'Goblet Squat',
    primaryMuscle: 'quads',
    secondaryMuscle: 'glutes',
    secondaryMuscles: ['glutes', 'abs'],
    category: 'legs',
    exerciseType: 'compound',
  },
  {
    id: 'ex-hack-squat',
    name: 'Hack Squat',
    primaryMuscle: 'quads',
    secondaryMuscle: 'glutes',
    secondaryMuscles: ['glutes', 'hamstrings'],
    category: 'legs',
    exerciseType: 'compound',
  },
  {
    id: 'ex-bulgarian-split-squat',
    name: 'Bulgarian Split Squat',
    primaryMuscle: 'quads',
    secondaryMuscle: 'glutes',
    secondaryMuscles: ['glutes', 'hamstrings'],
    category: 'legs',
    exerciseType: 'compound',
  },
  {
    id: 'ex-step-up',
    name: 'Step-Up',
    primaryMuscle: 'quads',
    secondaryMuscle: 'glutes',
    secondaryMuscles: ['glutes', 'hamstrings'],
    category: 'legs',
    exerciseType: 'compound',
  },
  {
    id: 'ex-sissy-squat',
    name: 'Sissy Squat',
    primaryMuscle: 'quads',
    category: 'legs',
    exerciseType: 'bodyweight',
  },
  {
    id: 'ex-pendulum-squat',
    name: 'Pendulum Squat',
    primaryMuscle: 'quads',
    secondaryMuscles: ['glutes'],
    category: 'legs',
    exerciseType: 'compound',
  },
  {
    id: 'ex-belt-squat',
    name: 'Belt Squat',
    primaryMuscle: 'quads',
    secondaryMuscles: ['glutes', 'hamstrings'],
    category: 'legs',
    exerciseType: 'compound',
  },
  {
    id: 'ex-single-leg-press',
    name: 'Single-Leg Press',
    primaryMuscle: 'quads',
    secondaryMuscles: ['glutes', 'hamstrings'],
    category: 'legs',
    exerciseType: 'compound',
  },
  {
    id: 'ex-reverse-lunge',
    name: 'Reverse Lunge',
    primaryMuscle: 'quads',
    secondaryMuscles: ['glutes', 'hamstrings'],
    category: 'legs',
    exerciseType: 'compound',
  },
  {
    id: 'ex-smith-squat',
    name: 'Smith Machine Squat',
    primaryMuscle: 'quads',
    secondaryMuscles: ['glutes', 'hamstrings'],
    category: 'legs',
    exerciseType: 'compound',
  },

  // ============================================================
  // HAMSTRINGS
  // ============================================================
  {
    id: 'ex-rdl',
    name: 'Romanian Deadlift',
    primaryMuscle: 'hamstrings',
    secondaryMuscle: 'glutes',
    secondaryMuscles: ['glutes', 'back'],
    category: 'legs',
    exerciseType: 'compound',
  },
  {
    id: 'ex-leg-curl',
    name: 'Leg Curl',
    primaryMuscle: 'hamstrings',
    category: 'legs',
    exerciseType: 'isolation',
  },
  {
    id: 'ex-stiff-leg-deadlift',
    name: 'Stiff-Leg Deadlift',
    primaryMuscle: 'hamstrings',
    secondaryMuscle: 'glutes',
    secondaryMuscles: ['glutes', 'back'],
    category: 'legs',
    exerciseType: 'compound',
  },
  {
    id: 'ex-seated-leg-curl',
    name: 'Seated Leg Curl',
    primaryMuscle: 'hamstrings',
    category: 'legs',
    exerciseType: 'isolation',
  },
  {
    id: 'ex-nordic-curl',
    name: 'Nordic Curl',
    primaryMuscle: 'hamstrings',
    secondaryMuscle: 'glutes',
    secondaryMuscles: ['glutes'],
    category: 'legs',
    exerciseType: 'bodyweight',
  },
  {
    id: 'ex-good-morning',
    name: 'Good Morning',
    primaryMuscle: 'hamstrings',
    secondaryMuscle: 'glutes',
    secondaryMuscles: ['glutes', 'back'],
    category: 'legs',
    exerciseType: 'compound',
  },
  {
    id: 'ex-cable-leg-curl',
    name: 'Cable Leg Curl',
    primaryMuscle: 'hamstrings',
    category: 'legs',
    exerciseType: 'isolation',
  },
  {
    id: 'ex-single-leg-rdl',
    name: 'Single-Leg Romanian Deadlift',
    primaryMuscle: 'hamstrings',
    secondaryMuscles: ['glutes', 'back'],
    category: 'legs',
    exerciseType: 'compound',
  },
  {
    id: 'ex-glute-ham-raise',
    name: 'Glute-Ham Raise',
    primaryMuscle: 'hamstrings',
    secondaryMuscles: ['glutes'],
    category: 'legs',
    exerciseType: 'bodyweight',
  },

  // ============================================================
  // GLUTES
  // ============================================================
  {
    id: 'ex-hip-thrust',
    name: 'Hip Thrust',
    primaryMuscle: 'glutes',
    secondaryMuscle: 'hamstrings',
    secondaryMuscles: ['hamstrings', 'quads'],
    category: 'legs',
    exerciseType: 'compound',
  },
  {
    id: 'ex-glute-bridge',
    name: 'Glute Bridge',
    primaryMuscle: 'glutes',
    secondaryMuscle: 'hamstrings',
    secondaryMuscles: ['hamstrings'],
    category: 'legs',
    exerciseType: 'bodyweight',
  },
  {
    id: 'ex-cable-pull-through',
    name: 'Cable Pull-Through',
    primaryMuscle: 'glutes',
    secondaryMuscle: 'hamstrings',
    secondaryMuscles: ['hamstrings', 'back'],
    category: 'legs',
    exerciseType: 'isolation',
  },
  {
    id: 'ex-cable-glute-kickback',
    name: 'Cable Glute Kickback',
    primaryMuscle: 'glutes',
    secondaryMuscle: 'hamstrings',
    secondaryMuscles: ['hamstrings'],
    category: 'legs',
    exerciseType: 'isolation',
  },
  {
    id: 'ex-sumo-deadlift',
    name: 'Sumo Deadlift',
    primaryMuscle: 'glutes',
    secondaryMuscle: 'quads',
    secondaryMuscles: ['quads', 'hamstrings', 'back'],
    category: 'legs',
    exerciseType: 'compound',
  },
  {
    id: 'ex-donkey-kick',
    name: 'Donkey Kick',
    primaryMuscle: 'glutes',
    secondaryMuscle: 'hamstrings',
    secondaryMuscles: ['hamstrings'],
    category: 'legs',
    exerciseType: 'bodyweight',
  },
  {
    id: 'ex-frog-pump',
    name: 'Frog Pump',
    primaryMuscle: 'glutes',
    secondaryMuscles: ['hamstrings'],
    category: 'legs',
    exerciseType: 'bodyweight',
  },
  {
    id: 'ex-banded-clamshell',
    name: 'Banded Clamshell',
    primaryMuscle: 'glutes',
    category: 'legs',
    exerciseType: 'isolation',
  },
  {
    id: 'ex-smith-hip-thrust',
    name: 'Smith Machine Hip Thrust',
    primaryMuscle: 'glutes',
    secondaryMuscles: ['hamstrings', 'quads'],
    category: 'legs',
    exerciseType: 'compound',
  },

  // ============================================================
  // CALVES
  // ============================================================
  {
    id: 'ex-calf-raise',
    name: 'Calf Raise',
    primaryMuscle: 'calves',
    category: 'legs',
    exerciseType: 'isolation',
  },
  {
    id: 'ex-seated-calf-raise',
    name: 'Seated Calf Raise',
    primaryMuscle: 'calves',
    category: 'legs',
    exerciseType: 'isolation',
  },
  {
    id: 'ex-leg-press-calf-raise',
    name: 'Leg Press Calf Raise',
    primaryMuscle: 'calves',
    category: 'legs',
    exerciseType: 'isolation',
  },
  {
    id: 'ex-donkey-calf-raise',
    name: 'Donkey Calf Raise',
    primaryMuscle: 'calves',
    category: 'legs',
    exerciseType: 'isolation',
  },
  {
    id: 'ex-smith-calf-raise',
    name: 'Smith Machine Calf Raise',
    primaryMuscle: 'calves',
    category: 'legs',
    exerciseType: 'isolation',
  },
  {
    id: 'ex-single-leg-calf-raise',
    name: 'Single-Leg Calf Raise',
    primaryMuscle: 'calves',
    category: 'legs',
    exerciseType: 'isolation',
  },

  // ============================================================
  // ABS
  // ============================================================
  {
    id: 'ex-hanging-leg-raise',
    name: 'Hanging Leg Raise',
    primaryMuscle: 'abs',
    category: 'full_body',
    exerciseType: 'bodyweight',
  },
  {
    id: 'ex-cable-crunch',
    name: 'Cable Crunch',
    primaryMuscle: 'abs',
    category: 'full_body',
    exerciseType: 'isolation',
  },
  {
    id: 'ex-ab-wheel-rollout',
    name: 'Ab Wheel Rollout',
    primaryMuscle: 'abs',
    secondaryMuscle: 'shoulders',
    secondaryMuscles: ['shoulders', 'back'],
    category: 'full_body',
    exerciseType: 'bodyweight',
  },
  {
    id: 'ex-plank',
    name: 'Plank',
    primaryMuscle: 'abs',
    secondaryMuscle: 'shoulders',
    secondaryMuscles: ['shoulders'],
    category: 'full_body',
    exerciseType: 'bodyweight',
    isTimeBased: true,
  },
  {
    id: 'ex-side-plank',
    name: 'Side Plank',
    primaryMuscle: 'abs',
    category: 'full_body',
    exerciseType: 'bodyweight',
    isTimeBased: true,
  },
  {
    id: 'ex-russian-twist',
    name: 'Russian Twist',
    primaryMuscle: 'abs',
    category: 'full_body',
    exerciseType: 'bodyweight',
  },
  {
    id: 'ex-bicycle-crunch',
    name: 'Bicycle Crunch',
    primaryMuscle: 'abs',
    category: 'full_body',
    exerciseType: 'bodyweight',
  },
  {
    id: 'ex-decline-sit-up',
    name: 'Decline Sit-Up',
    primaryMuscle: 'abs',
    category: 'full_body',
    exerciseType: 'bodyweight',
  },
  {
    id: 'ex-cable-woodchop',
    name: 'Cable Woodchop',
    primaryMuscle: 'abs',
    secondaryMuscle: 'shoulders',
    secondaryMuscles: ['shoulders'],
    category: 'full_body',
    exerciseType: 'isolation',
  },
  {
    id: 'ex-mountain-climbers',
    name: 'Mountain Climbers',
    primaryMuscle: 'abs',
    secondaryMuscle: 'shoulders',
    secondaryMuscles: ['shoulders', 'quads'],
    category: 'full_body',
    exerciseType: 'bodyweight',
  },
  {
    id: 'ex-v-up',
    name: 'V-Up',
    primaryMuscle: 'abs',
    category: 'full_body',
    exerciseType: 'bodyweight',
  },
  {
    id: 'ex-flutter-kick',
    name: 'Flutter Kick',
    primaryMuscle: 'abs',
    secondaryMuscles: ['quads'],
    category: 'full_body',
    exerciseType: 'bodyweight',
  },
  {
    id: 'ex-dead-bug',
    name: 'Dead Bug',
    primaryMuscle: 'abs',
    category: 'full_body',
    exerciseType: 'bodyweight',
  },
  {
    id: 'ex-hollow-hold',
    name: 'Hollow Hold',
    primaryMuscle: 'abs',
    category: 'full_body',
    exerciseType: 'bodyweight',
  },
  {
    id: 'ex-pallof-press',
    name: 'Pallof Press',
    primaryMuscle: 'abs',
    secondaryMuscles: ['shoulders'],
    category: 'full_body',
    exerciseType: 'isolation',
  },
  {
    id: 'ex-toes-to-bar',
    name: 'Toes-to-Bar',
    primaryMuscle: 'abs',
    secondaryMuscles: ['back', 'forearms'],
    category: 'full_body',
    exerciseType: 'bodyweight',
  },
  {
    id: 'ex-dragon-flag',
    name: 'Dragon Flag',
    primaryMuscle: 'abs',
    secondaryMuscles: ['back'],
    category: 'full_body',
    exerciseType: 'bodyweight',
  },

  // ============================================================
  // CARDIO
  // ============================================================
  // Running
  {
    id: 'ex-outdoor-run',
    name: 'Outdoor Running',
    primaryMuscle: 'cardio',
    secondaryMuscles: ['quads', 'hamstrings', 'calves'],
    category: 'cardio',
    exerciseType: 'cardio',
  },
  {
    id: 'ex-treadmill',
    name: 'Indoor Running (Treadmill)',
    primaryMuscle: 'cardio',
    secondaryMuscles: ['quads', 'hamstrings', 'calves'],
    category: 'cardio',
    exerciseType: 'cardio',
  },
  {
    id: 'ex-trail-running',
    name: 'Trail Running',
    primaryMuscle: 'cardio',
    secondaryMuscles: ['quads', 'hamstrings', 'calves', 'glutes'],
    category: 'cardio',
    exerciseType: 'cardio',
  },
  {
    id: 'ex-treadmill-walking',
    name: 'Treadmill Walking',
    primaryMuscle: 'cardio',
    secondaryMuscles: ['quads', 'glutes'],
    category: 'cardio',
    exerciseType: 'cardio',
  },
  {
    id: 'ex-incline-walking',
    name: 'Incline Walking',
    primaryMuscle: 'cardio',
    secondaryMuscles: ['quads', 'glutes', 'calves'],
    category: 'cardio',
    exerciseType: 'cardio',
  },
  {
    id: 'ex-sprint-intervals',
    name: 'Sprint Intervals',
    primaryMuscle: 'cardio',
    secondaryMuscles: ['quads', 'hamstrings', 'glutes', 'calves'],
    category: 'cardio',
    exerciseType: 'cardio',
  },
  {
    id: 'ex-stair-running',
    name: 'Stair Running',
    primaryMuscle: 'cardio',
    secondaryMuscles: ['quads', 'glutes', 'calves'],
    category: 'cardio',
    exerciseType: 'cardio',
  },
  // Cycling
  {
    id: 'ex-outdoor-biking',
    name: 'Outdoor Biking',
    primaryMuscle: 'cardio',
    secondaryMuscles: ['quads', 'hamstrings', 'glutes'],
    category: 'cardio',
    exerciseType: 'cardio',
  },
  {
    id: 'ex-stationary-bike',
    name: 'Indoor Biking (Stationary)',
    primaryMuscle: 'cardio',
    secondaryMuscle: 'quads',
    secondaryMuscles: ['quads', 'hamstrings'],
    category: 'cardio',
    exerciseType: 'cardio',
  },
  {
    id: 'ex-assault-bike',
    name: 'Assault Bike',
    primaryMuscle: 'cardio',
    secondaryMuscle: 'quads',
    secondaryMuscles: ['quads', 'shoulders'],
    category: 'cardio',
    exerciseType: 'cardio',
  },
  // Swimming
  {
    id: 'ex-swimming-pool',
    name: 'Swimming (Pool)',
    primaryMuscle: 'cardio',
    secondaryMuscles: ['back', 'shoulders', 'abs'],
    category: 'cardio',
    exerciseType: 'cardio',
  },
  {
    id: 'ex-open-water-swimming',
    name: 'Open Water Swimming',
    primaryMuscle: 'cardio',
    secondaryMuscles: ['back', 'shoulders', 'abs'],
    category: 'cardio',
    exerciseType: 'cardio',
  },
  // Machines
  {
    id: 'ex-rowing',
    name: 'Rowing Machine',
    primaryMuscle: 'cardio',
    secondaryMuscle: 'back',
    secondaryMuscles: ['back', 'shoulders', 'quads'],
    category: 'cardio',
    exerciseType: 'cardio',
  },
  {
    id: 'ex-stairmaster',
    name: 'StairMaster',
    primaryMuscle: 'cardio',
    secondaryMuscle: 'quads',
    secondaryMuscles: ['quads', 'glutes', 'calves'],
    category: 'cardio',
    exerciseType: 'cardio',
  },
  {
    id: 'ex-elliptical',
    name: 'Elliptical',
    primaryMuscle: 'cardio',
    secondaryMuscle: 'quads',
    secondaryMuscles: ['quads', 'glutes'],
    category: 'cardio',
    exerciseType: 'cardio',
  },
  {
    id: 'ex-ski-erg',
    name: 'Ski Erg',
    primaryMuscle: 'cardio',
    secondaryMuscles: ['back', 'shoulders', 'abs'],
    category: 'cardio',
    exerciseType: 'cardio',
  },
  {
    id: 'ex-versaclimber',
    name: 'VersaClimber',
    primaryMuscle: 'cardio',
    secondaryMuscles: ['quads', 'glutes', 'shoulders'],
    category: 'cardio',
    exerciseType: 'cardio',
  },
  // Other cardio
  {
    id: 'ex-jump-rope',
    name: 'Jump Rope',
    primaryMuscle: 'cardio',
    secondaryMuscle: 'calves',
    secondaryMuscles: ['calves', 'shoulders'],
    category: 'cardio',
    exerciseType: 'cardio',
  },
  {
    id: 'ex-hiking',
    name: 'Hiking',
    primaryMuscle: 'cardio',
    secondaryMuscles: ['quads', 'glutes', 'calves', 'hamstrings'],
    category: 'cardio',
    exerciseType: 'cardio',
  },
  {
    id: 'ex-battle-ropes',
    name: 'Battle Ropes',
    primaryMuscle: 'cardio',
    secondaryMuscle: 'shoulders',
    secondaryMuscles: ['shoulders', 'abs'],
    category: 'cardio',
    exerciseType: 'cardio',
  },
  {
    id: 'ex-sled-push',
    name: 'Sled Push',
    primaryMuscle: 'cardio',
    secondaryMuscle: 'quads',
    secondaryMuscles: ['quads', 'glutes', 'calves'],
    category: 'cardio',
    exerciseType: 'cardio',
  },
  {
    id: 'ex-sled-pull',
    name: 'Sled Pull',
    primaryMuscle: 'cardio',
    secondaryMuscles: ['back', 'hamstrings', 'glutes'],
    category: 'cardio',
    exerciseType: 'cardio',
  },
  // Training types
  {
    id: 'ex-hiit-cardio',
    name: 'HIIT Cardio',
    primaryMuscle: 'cardio',
    secondaryMuscles: ['quads', 'abs'],
    category: 'cardio',
    exerciseType: 'cardio',
  },
  {
    id: 'ex-steady-state-cardio',
    name: 'Steady-State Cardio',
    primaryMuscle: 'cardio',
    category: 'cardio',
    exerciseType: 'cardio',
  },

  // ============================================================
  // FULL BODY
  // ============================================================
  {
    id: 'ex-power-clean',
    name: 'Power Clean',
    primaryMuscle: 'full_body',
    secondaryMuscle: 'quads',
    secondaryMuscles: ['quads', 'back', 'shoulders', 'hamstrings'],
    category: 'full_body',
    exerciseType: 'compound',
  },
  {
    id: 'ex-power-snatch',
    name: 'Power Snatch',
    primaryMuscle: 'full_body',
    secondaryMuscle: 'shoulders',
    secondaryMuscles: ['shoulders', 'back', 'quads', 'hamstrings'],
    category: 'full_body',
    exerciseType: 'compound',
  },
  {
    id: 'ex-burpee',
    name: 'Burpee',
    primaryMuscle: 'full_body',
    secondaryMuscle: 'chest',
    secondaryMuscles: ['chest', 'quads', 'shoulders'],
    category: 'full_body',
    exerciseType: 'bodyweight',
  },
  {
    id: 'ex-kettlebell-swing',
    name: 'Kettlebell Swing',
    primaryMuscle: 'full_body',
    secondaryMuscle: 'glutes',
    secondaryMuscles: ['glutes', 'hamstrings', 'shoulders', 'abs'],
    category: 'full_body',
    exerciseType: 'compound',
  },
  {
    id: 'ex-thrusters',
    name: 'Thrusters',
    primaryMuscle: 'full_body',
    secondaryMuscle: 'quads',
    secondaryMuscles: ['quads', 'shoulders', 'triceps'],
    category: 'full_body',
    exerciseType: 'compound',
  },
  {
    id: 'ex-turkish-get-up',
    name: 'Turkish Get-Up',
    primaryMuscle: 'full_body',
    secondaryMuscle: 'shoulders',
    secondaryMuscles: ['shoulders', 'abs', 'glutes'],
    category: 'full_body',
    exerciseType: 'compound',
  },
  {
    id: 'ex-clean-and-jerk',
    name: 'Clean and Jerk',
    primaryMuscle: 'full_body',
    secondaryMuscles: ['quads', 'shoulders', 'back', 'hamstrings'],
    category: 'full_body',
    exerciseType: 'compound',
  },
  {
    id: 'ex-snatch',
    name: 'Snatch',
    primaryMuscle: 'full_body',
    secondaryMuscles: ['shoulders', 'back', 'quads', 'hamstrings'],
    category: 'full_body',
    exerciseType: 'compound',
  },
  {
    id: 'ex-man-maker',
    name: 'Man Maker',
    primaryMuscle: 'full_body',
    secondaryMuscles: ['chest', 'shoulders', 'quads', 'back'],
    category: 'full_body',
    exerciseType: 'compound',
  },
  {
    id: 'ex-wall-ball',
    name: 'Wall Ball',
    primaryMuscle: 'full_body',
    secondaryMuscles: ['quads', 'shoulders', 'glutes'],
    category: 'full_body',
    exerciseType: 'compound',
  },
  {
    id: 'ex-box-jump',
    name: 'Box Jump',
    primaryMuscle: 'full_body',
    secondaryMuscles: ['quads', 'glutes', 'calves'],
    category: 'full_body',
    exerciseType: 'bodyweight',
  },
  {
    id: 'ex-devil-press',
    name: 'Devil Press',
    primaryMuscle: 'full_body',
    secondaryMuscles: ['chest', 'shoulders', 'quads'],
    category: 'full_body',
    exerciseType: 'compound',
  },

  // ============================================================
  // MOBILITY
  // ============================================================
  {
    id: 'ex-foam-rolling',
    name: 'Foam Rolling',
    primaryMuscle: 'full_body',
    category: 'full_body',
    exerciseType: 'mobility',
  },
  {
    id: 'ex-band-pull-apart',
    name: 'Band Pull-Apart',
    primaryMuscle: 'shoulders',
    secondaryMuscle: 'back',
    secondaryMuscles: ['back'],
    category: 'shoulders',
    exerciseType: 'mobility',
  },
  {
    id: 'ex-wall-slides',
    name: 'Wall Slides',
    primaryMuscle: 'shoulders',
    category: 'shoulders',
    exerciseType: 'mobility',
  },
  {
    id: 'ex-hip-flexor-stretch',
    name: 'Hip Flexor Stretch',
    primaryMuscle: 'quads',
    secondaryMuscle: 'glutes',
    secondaryMuscles: ['glutes'],
    category: 'legs',
    exerciseType: 'mobility',
  },
  {
    id: 'ex-pigeon-stretch',
    name: 'Pigeon Stretch',
    primaryMuscle: 'glutes',
    secondaryMuscles: ['quads'],
    category: 'legs',
    exerciseType: 'mobility',
  },
  {
    id: 'ex-cat-cow',
    name: 'Cat-Cow Stretch',
    primaryMuscle: 'back',
    secondaryMuscles: ['abs'],
    category: 'full_body',
    exerciseType: 'mobility',
  },
  {
    id: 'ex-worlds-greatest-stretch',
    name: "World's Greatest Stretch",
    primaryMuscle: 'full_body',
    secondaryMuscles: ['quads', 'hamstrings', 'shoulders'],
    category: 'full_body',
    exerciseType: 'mobility',
  },
];
